# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ilyas
tagline:          'Full Stack Developer'
description:      'JavaScript, VueJS, NodeJS PHP, Laravel, Kubernetes, Docker, CI/CD'
url:              https://ilyasdeckers.github.io/blog/
baseurl:          /

author:
  name:           'Ilyas Deckers'
  url:            https://ilyasdeckers.be

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ilyasdeckers
